name: Build

on: push

jobs:
  build:
    name: Phar building
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Build]')"

    steps:
      - name: Startup
        uses: actions/checkout@v3
      - name: Checkout PharBuilder
        uses: actions/checkout@v3
        with:
          repository: NetherGamesMC/PharBuilder
          token: ${{ secrets.ng_token }}
          path: PharBuilder
          ref: pm5
      - name: Download PHP Release
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: Linux.zip
          repo: NetherGamesMC/php-build-scripts
          version: "tags/8.2-pm5"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unpack PHP Release
        run: unzip Linux.zip && tar -xzvf PHP_Linux-x86_64.tar.gz
      - name: Download pharbuilder-rs
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: pharbuilder
          repo: NetherGamesMC/pharbuilder-rs
          token: ${{ secrets.ng_token }}
      - name: Build
        run: |
          echo Building...
          chmod +x pharbuilder
          ./pharbuilder -i . -o PharBuilder/Mineceit.phar
          echo Injecting Virions...
          ./bin/php7/bin/php -dphar.readonly=0 PharBuilder/SimplePacketHandler.phar PharBuilder/BlockLagFix.phar
          echo Build completed!
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: BlockLagFix
          path: PharBuilder/Mineceit.phar
